export enum Errors {
    ERR_INVALID_LOGINPASS = 'ERR_INVALID_LOGINPASS',
    ERR_NOT_ENOUGHT_RIGHTS = 'ERR_NOT_ENOUGHT_RIGHTS',
    ERR_INVALID_INPUT_DATA = 'ERR_INVALID_INPUT_DATA',
    ERR_AGREEMENT_REQUIRED = "ERR_AGREEMENT_REQUIRED",
    ERR_APPLICATION_NOT_AUTHORIZED = "ERR_APPLICATION_NOT_AUTHORIZED",
    ERR_USER_NOT_AUTHORIZED = "ERR_USER_NOT_AUTHORIZED",
    ERR_INVALID_USER = "ERR_INVALID_USER",
    ERR_TOKEN_EXPIRED = "ERR_TOKEN_EXPIRED",
    ERR_INVALID_DATA = "ERR_INVALID_DATA",
}