export enum Providers {
    SEQUELIZE = 'SEQUELIZE',
    MODEL_USER = "MODEL_USER",
    MODEL_ROLE = "MODEL_ROLE",
    MODEL_FILE = "MODEL_FILE",
    MODEL_STORE = "MODEL_STORE",
    MODEL_ITEM = "MODEL_ITEM",
    MODEL_PROPERTY_VALUE = "MODEL_PROPERTY_VALUE",
    MODEL_PROPERTY = "MODEL_PROPERTY",
    MODEL_SHOP = "MODEL_SHOP"
}